### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by xzl1996** [ICascha/QuantGANs-replication#1]
dear ICascha:
I'm very interested in your project,I want to know the environment of running this code.
Can you expose the environment in which this code runs.and the tensorflow version.
Thanks!!!

With my good wishes!
Yours,
xzl

**Comment by ICascha** [comment]
Dear xzl1996,

Python version is 3.7.10. Tensorflow version is 2.4.1. I ran all experiments on google Colab. (Data was obtained from yahoo finance). I found no big problems on tensorflow 2.5 either. If you run into any issues, let me know, I'm quite busy a the moment but will be able to help for sure after this month.

Sincerely,

Cascha van Wanrooij

**Comment by xzl1996** [comment]
> Dear xzl1996,
> 
> Python version is 3.7.10. Tensorflow version is 2.4.1. I ran all experiments on google Colab. (Data was obtained from yahoo finance). I found no big problems on tensorflow 2.5 either. If you run into any issues, let me know, I'm quite busy a the moment but will be able to help for sure after this month.
> 
> Sincerely,
> 
> Cascha van Wanrooij

Dear ICascha:
Thank you very much for your reply, which is very useful to me.
Looking forward to the follow-up communication.

Sincerely,
xzl
